In [1]:
# SCALARS

temperature = 25

print(f"The temperature is {temperature}℃.")

The temperature is 25°C.


In [3]:
score = 89.99

print(f"The student's score is {score}.")

The student's score is 89.99.


In [9]:
# VECTORS - list having same type of values, list of similar items

days_of_week = ['Monday', 'Tuesday', 'Wednesday' , 'Thursday', 'Friday', 'Saturday' , 'Sunday']
print("Days of the week are: ", ", ".join(days_of_week))

Days of the week are:  Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday


In [17]:
monthly_rainfall = [35,24,89,23,75,64,45,56,34]
print("Monthly rainfall:" , monthly_rainfall)


Monthly rainfall: [35, 24, 89, 23, 75, 64, 45, 56, 34]


In [21]:
# LISTS - containing different types of items

mixed_bag = [42,'banana',3.14, False]
print ("Mixed Bag", mixed_bag)


Mixed Bag [42, 'banana', 3.14, False]


In [27]:
student_info = ['John Doe', 20 ,'Computer Science',3.5]
print ("student information: " , student_info)

student information:  ['John Doe', 20, 'Computer Science', 3.5]


In [35]:
# ARRAYS - multidimensional grid of values

# 2d array

import numpy as np

coordinates = np.array([[1,2], [3,4], [5,6]])
print("Coordinates:\n" , coordinates)

Coordinates:
 [[1 2]
 [3 4]
 [5 6]]


In [37]:
import numpy as np

pixel_intensities = np.array([[255, 128, 0] , [64, 32, 16] , [8, 4, 2]])
print("Pixel intensitiess:\n" , pixel_intensities)


Pixel intensitiess:
 [[255 128   0]
 [ 64  32  16]
 [  8   4   2]]


In [43]:
# FACTORS - categorical data objects

import pandas as pd
responses = pd.Categorical(['Yes', 'No', 'Yes', 'No', 'Maybe'])
print ("Survey Responses:", responses)


Survey Responses: ['Yes', 'No', 'Yes', 'No', 'Maybe']
Categories (3, object): ['Maybe', 'No', 'Yes']


In [49]:
import pandas as pd
shirt_sizes = pd.Categorical(['M' , 'L' , 'S' , 'M' , 'XL' , 'L'])

print ("Shirt Sizes:" , shirt_sizes)


Shirt Sizes: ['M', 'L', 'S', 'M', 'XL', 'L']
Categories (4, object): ['L', 'M', 'S', 'XL']


In [59]:
# DATAFRAME - 2d labeled data

grades_data = {'Name' : ['Alice' , 'Bob' , 'Charlie'],
'Math' : [85 , 90 , 95],
'Science' : [92 , 88 , 85]}

grades_df = pd.DataFrame(grades_data)
print("Class Grades:\n" , grades_df)


Class Grades:
       Name  Math  Science
0    Alice    85       92
1      Bob    90       88
2  Charlie    95       85


In [77]:
products_df = pd.read_csv('products.csv')
print ("Products from csv:\n" , products_df)

Products from csv:
       Product  Price   Stock
0      Laptop   1200      30
1      Tablet    300      50
2  Smartphone    800     100


In [75]:
print ("Summary Statistics:\n" , products_df.describe())
print ("Data types:\n" , products_df.dtypes)

Summary Statistics:
              Price       Stock
count     3.000000    3.000000
mean    766.666667   60.000000
std     450.924975   36.055513
min     300.000000   30.000000
25%     550.000000   40.000000
50%     800.000000   50.000000
75%    1000.000000   75.000000
max    1200.000000  100.000000
Data types:
 Product    object
Price       int64
 Stock      int64
dtype: object


In [107]:
titanic_df = pd.read_csv('Titanic-Dataset.csv')
titanic_df.describe()

num_passengers = len(titanic_df)
print (f"Number of passengers: {num_passengers}")


Number of passengers: 891


In [11]:
import pandas as pd
titanic_df = pd.read_csv('Titanic-Dataset.csv')
passenger_names = titanic_df['Name'].tolist()
print ("First 5 passenger names:" , passenger_names[:5])

First 5 passenger names: ['Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss. Laina', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Allen, Mr. William Henry']


In [25]:
import pandas as pd
titanic_df = pd.read_csv('Titanic-Dataset.csv')
five_passenger_info = []

print("Five passenger information: ")
for i in range(5):
    passenger = titanic_df.iloc[i].tolist()
    print(passenger)


Five passenger information: 
[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0, 'A/5 21171', 7.25, nan, 'S']
[2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C']
[3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0, 'STON/O2. 3101282', 7.925, nan, 'S']
[4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S']
[5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0, '373450', 8.05, nan, 'S']


In [29]:
import pandas as pd
import numpy as np

titanic_df = pd.read_csv('Titanic-Dataset.csv')

# FACTOR
class_factor = pd.Categorical(titanic_df['Pclass'].dropna())
print ("Passenger class categories:" , class_factor.categories)
print()
embarked_factor = pd.Categorical(titanic_df['Embarked'].dropna())
print ("Embarked location categories:" , embarked_factor.categories)

Passenger class categories: Index([1, 2, 3], dtype='int64')

Embarked location categories: Index(['C', 'Q', 'S'], dtype='object')


In [36]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [33]:

print ("\nSummary statistics :\n" , titanic_df.describe())


Summary statistics :
        PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  
